/* { dg-do run } */

fun foo = int:
  {
   try
     raise Exception {code = 1};
   catch (Exception e)
   {
     raise e;
   }
   return 666;
  }

fun bar = int:
  {
   try
     return foo;
   catch
   {
     print ("caught exception\n");
   }

   return 0;
  }

/* { dg-command {  bar } } */
/* { dg-output "caught exception\n0" } */
